#!/bin/env bash

# This script is my environment specific.

if [[ -z "$1" ]]; then
  DIR="$HOME/shared/Books_Latest"
  TARGET=$(find "$DIR" -type f -iname "*.pdf" -printf '%P\n' | fzf)
  [ -n "$TARGET" ] && zathura "$DIR/$TARGET" > /dev/null 2>&1 &
else
  [ -f "$1" ] && zathura "$1" > /dev/null &
fi
