#!/bin/env bash

SESSION_NAME=""

if [[ -z "$1" ]]; then
  if is-there gum > /dev/null; then
    SESSION_NAME=$(gum input --prompt="Session Name : " --placeholder="ENV")
  else
    printf "Enter session name : "
    read -r SESSION_NAME
  fi
else
  SESSION_NAME="$1"
fi

SESSION_EDITOR=$(gum choose helix nvim vim)

SESSION_EXISTS=$(tmux list-sessions | grep $SESSION_NAME)

if [ "$SESSION_EXISTS" == "" ]; then
  tmux new-session -d -s $SESSION_NAME

  tmux rename-window -t 1 "ZSH"
  tmux send-keys -t "ZSH" "clear" C-m

  tmux new-window -t $SESSION_NAME:2 -n "${SESSION_EDITOR^^}"
  tmux send-keys -t "${SESSION_EDITOR^^}" "$SESSION_EDITOR ." C-m
fi

tmux attach-session -t $SESSION_NAME:1

