#!/bin/bash

# Function to check if the battery is low and send notification
check_low_bt() {

	# Battery percentage
	percentage="$(upower -i "$(upower -e | grep BAT)" | grep percentage | awk '{print $2}' | tr -d '%')"

	# Send notification if the number is less than 15
	if [[ "$percentage" -lt 15 ]]; then
		notify-send "Alert" "Low Battery: $percentage%"
	fi
}

check_low_bt
