#!/bin/env bash

set -e

is_there() {
  command -v "$1" >/dev/null 2>&1
}

check_dependencies() {
  if ! is_there nmcli ; then
    echo "nmcli not found. Please install NetworkManager."
    exit 1
  fi

  if ! is_there dmenu ; then
    echo "dmenu not found. Please install dmenu."
    exit 1
  fi
}

# Parameters:
# $1 = ssid
connect_with_password() {
  password=$(echo "" | dmenu -P -p "Enter password for $1: ")
  [ -z "$password" ] && exit 0;

  if nmcli device wifi connect "$1" password "$password"; then
    notify-send "WiFi" "Connected to $1"
  else
    notify-send "WiFi" "Failed to connect to $1. Check password."
  fi
}

main() {
  check_dependencies

  nmcli radio wifi on

  # Scan and optain networks
  notify-send "WiFi" "Scanning for networks.." 2>/dev/null &
  nmcli device wifi rescan 2>/dev/null
  networks=$(nmcli -f SSID,SECURITY,BARS device wifi list | tail -n +2)
  if [ -z "$networks" ]; then
    notify-send "WiFi" "No Networks Found.."
    exit
  fi

  # Select network with dmenu
  selected=$(echo "$networks" | dmenu -i -l 20 -p "Select WiFi Network:")
  [ -z "$selected" ] && exit 0;

  ssid=$(echo "$selected" | awk '{$NF=""; $(NF-1)=""; print $0}' | sed 's/[[:space:]]*$//')

  # Check if already saved
  saved_connections=$(nmcli -g NAME connection show)

  if echo "$saved_connections" | grep -Fxq "$ssid"; then
    if nmcli connection up "$ssid"; then
      notify-send "WiFi" "Connected to $ssid"
    else
      notify-send "WiFi" "Failed to connect to $ssid"

      # Connection failed, ask if user wants to re-enter password
      retry=$(echo -e "Yes\nNo" | dmenu -p "Connection failed. Re-enter password?")
      [ "$retry" != "Yes" ] && exit

      nmcli connection delete "$ssid" >/dev/null 2>&1

      connect_with_password "$ssid"
    fi
  else
    connect_with_password "$ssid"
  fi
}

main "$@"
