#!/bin/env bash

set -e

# Parameters:
# $1 = program_name
is_there() {
  command -v "$1" >/dev/null 2>&1
}

check_dependencies() {
  if ! is_there nmcli ; then
    echo "nmcli not found. Please install NetworkManager."
    exit 1
  fi

  if ! is_there dmenu ; then
    echo "dmenu not found. Please install dmenu."
    exit 1
  fi
}

current_network() {
  current_network=$(nmcli -t -f NAME connection show --active | grep -v "lo" | head -n 1)
  if [ -z "$current_network" ]; then
    echo "No Connection"
  else
    echo "$current_network"
  fi
}

# Parameters:
# $1 = ssid
connect_with_password() {
  password=$(echo "" | dmenu -P -p "Enter password for $1: ")
  [ -z "$password" ] && exit 0;

  if nmcli device wifi connect "$1" password "$password"; then
    notify-send "WiFi" "Connected to $1"
  else
    notify-send "WiFi" "Failed to connect to $1. Check password."
  fi
}

main() {
  check_dependencies

  nmcli radio wifi on

  # Scan and optain networks
  curr_network="$(current_network)"
  notify-send "WiFi" "Scanning for networks... ($curr_network)" 2>/dev/null &
  nmcli device wifi rescan 2>/dev/null
  networks=$(nmcli -f SSID,BSSID,SECURITY,FREQ,SIGNAL,BARS device wifi list | tail -n +2)
  if [ -z "$networks" ]; then
    notify-send "WiFi" "No Networks Found.."
    exit
  fi

  # Add disconnect and rescan options
  if [ "$curr_network" != "No connection" ]; then
    networks="$networks
󰖪 Disconnect from $curr_network
󰑓 Rescan Networks"
  else
    networks="$networks
󰑓 Rescan Networks"
  fi

  # Select network with dmenu
  selected=$(echo "$networks" | dmenu -i -l 20 -p "Select WiFi Network:")
  [ -z "$selected" ] && exit 0;

  # Handle disconnect and rescan options
  if [[ "$selected" == "󰖪 Disconnect"* ]]; then
    nmcli connection down "$curr_network" 2>/dev/null
    notify-send "WiFi" "Disconnected from $curr_network" 2>/dev/null
    exit 0
  fi

  if [[ "$selected" == "󰑓 Rescan"* ]]; then
    exec "$0"
  fi

  ssid=$(echo "$selected" | awk '{print $1}')

  # Check if already saved
  saved_connections=$(nmcli -g NAME connection show)

  if echo "$saved_connections" | grep -Fxq "$ssid"; then
    if nmcli connection up "$ssid"; then
      notify-send "WiFi" "Connected to $ssid"
    else
      notify-send "WiFi" "Failed to connect to $ssid"

      # Connection failed, ask if user wants to re-enter password
      retry=$(echo -e "Yes\nNo" | dmenu -p "Connection failed. Re-enter password?")
      [ "$retry" != "Yes" ] && exit

      nmcli connection delete "$ssid" >/dev/null 2>&1

      connect_with_password "$ssid"
    fi
  else
    connect_with_password "$ssid"
  fi
}

main "$@"
